# Generated by Django 5.2.4 on 2025-07-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Resposta Texto')),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resposta Número')),
                ('answer_boolean', models.BooleanField(blank=True, null=True, verbose_name='Resposta Sim/Não')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta da Atividade',
                'verbose_name_plural': 'Respostas das Atividades',
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activity_photos/', verbose_name='Foto')),
                ('photo_type', models.CharField(choices=[('before', 'Antes'), ('during', 'Durante'), ('after', 'Depois'), ('problem', 'Problema'), ('solution', 'Solução')], max_length=10, verbose_name='Tipo da Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Tirada em')),
            ],
            options={
                'verbose_name': 'Foto da Atividade',
                'verbose_name_plural': 'Fotos das Atividades',
                'ordering': ['taken_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Atividade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('estimated_time', models.DurationField(blank=True, null=True, verbose_name='Tempo Estimado')),
                ('requires_parts', models.BooleanField(default=True, verbose_name='Requer Peças')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipos de Atividades',
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Utilizada')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uso de Peça',
                'verbose_name_plural': 'Uso de Peças',
            },
        ),
        migrations.CreateModel(
            name='StandardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('question_type', models.CharField(choices=[('yes_no', 'Sim/Não'), ('text', 'Texto'), ('number', 'Número'), ('multiple_choice', 'Múltipla Escolha')], max_length=15, verbose_name='Tipo da Pergunta')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='Opções (para múltipla escolha)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Pergunta Padrão',
                'verbose_name_plural': 'Perguntas Padrão',
                'ordering': ['activity_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=15, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Agendada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Duração Estimada')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Duração Real')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype', verbose_name='Tipo de Atividade')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Atividade de Manutenção',
                'verbose_name_plural': 'Atividades de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
    ]
