name: maintenance_app
description: "Sistema de Relatório de Manutenção - App móvel para técnicos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI e Navegação
  cupertino_icons: ^1.0.8
  
  # Gerenciamento de Estado
  provider: ^6.1.2
  
  # HTTP e API
  http: ^1.2.0
  dio: ^5.4.0
  
  # Armazenamento Local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # QR Code
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.1.0
  
  # Câmera e Fotos
  camera: ^0.10.5+7
  image_picker: ^1.0.7
  
  # Permissões
  permission_handler: ^11.3.0
  
  # UI Components
  flutter_speed_dial: ^7.0.0
  cached_network_image: ^3.3.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
