# Generated by Django 5.2.4 on 2025-07-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Local')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Local')),
                ('location_type', models.CharField(choices=[('plant', 'Planta/Fábrica'), ('sector', 'Setor'), ('line', 'Linha de Produção'), ('equipment', 'Equipamento'), ('component', 'Componente'), ('area', 'Área')], max_length=10, verbose_name='Tipo de Local')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location', verbose_name='Local Pai')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['parent', 'name'],
            },
        ),
    ]
